apiVersion: apps/v1
kind: Deployment
metadata:
  name: visitor-counter
  namespace: spacely
spec:
  replicas: 2
  selector:
    matchLabels:
      app: visitor-counter
  template:
    metadata:
      labels:
        app: visitor-counter
    spec:
      containers:
      - name: visitor-counter
        image: spacelysprockets.azurecr.io/visitor-counter:1.0.0
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: acr-credentials
